name: Update CSV File

on:
  schedule:
    - cron: '0 * * * *'  # This runs the workflow every hour
  push:
    branches:
      - main

jobs:
  scrape:
    strategy:
      matrix:
        offset: [0, 200, 400, 600, 800, 1000, 1200, 1400, 1600, 1800, 2000, 2200, 2400, 2600, 2800, 3000]
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.x

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests beautifulsoup4 pandas

      - name: Run scraper and save to temp file
        run: |
          python scraper.py ${{ matrix.offset }}

      - name: Upload temp file
        uses: actions/upload-artifact@v2
        with:
          name: temp-file-${{ matrix.offset }}
          path: temp_${{ matrix.offset }}.csv

      - name: List files
        run: ls -l

  consolidate:
    needs: scrape
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: List all artifacts
        id: list-artifacts
        run: |
          echo "Listing all artifacts"
          curl -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
            -H "Accept: application/vnd.github.v3+json" \
            https://api.github.com/repos/${{ github.repository }}/actions/artifacts | jq -r '.artifacts[] | select(.name | startswith("temp-file-")) | .name' > artifact_names.txt
          cat artifact_names.txt

      # - name: Download all artifacts
      #   uses: actions/download-artifact@v2
      #   with:
      #     name: temp-file-*
      #     path: artifacts
      - name: Download all workflow run artifacts
        uses: actions/download-artifact@v4
        with:
          merge-multiple: true
      - name: Display structure of downloaded files
        run: ls -R      
        # - name: Download all artifacts
      #   env:
      #     GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      #   run: |
      #     mkdir artifacts
      #     while IFS= read -r artifact; do
      #       echo "Downloading $artifact"
      #       gh run download $artifact --dir artifacts
      #     done < artifact_names.txt

      - name: Sort and list artifact files
        run: |
          ls artifacts/temp_*.csv | sort -t '_' -k 2 -n > sorted_files.txt
          cat sorted_files.txt

      - name: Consolidate results into data.csv
        run: |
          echo "" > final_results.csv  # Ensure file is empty before appending
          while IFS= read -r file; do
            cat "$file" >> final_results.csv
          done < sorted_files.txt

      - name: Commit and push consolidated results
        env:
          PAT_TOKEN: ${{ secrets.PAT_TOKEN }}
        run: |
          chmod +x git_update.sh
          ./git_update.sh



