name: Update CSV File

on:
  schedule:
    - cron: '0 * * * *'  # This runs the workflow every hour
  push:
    branches:
      - main

jobs:
  scrape:
    strategy:
      matrix:
        offset: [0, 200, 400, 600, 800, 1000, 1200, 1400, 1600, 1800, 2000, 2200, 2400, 2600, 2800, 3000]
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.x

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests beautifulsoup4 pandas

      - name: Run scraper and save to temp file
        run: |
          echo "Running scraper with offset ${{ matrix.offset }}"
          python scraper.py ${{ matrix.offset }}

      - name: Upload temp file
        uses: actions/upload-artifact@v4
        with:
          name: temp-file-${{ matrix.offset }}
          path: temp_${{ matrix.offset }}.zip

      - name: List files
        run: ls -l

  consolidate:
    needs: scrape
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: List all artifacts
        id: list-artifacts
        run: |
          echo "Listing all artifacts"
          curl -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
            -H "Accept: application/vnd.github.v3+json" \
            https://api.github.com/repos/${{ github.repository }}/actions/artifacts | jq -r '.artifacts[] | select(.name | startswith("temp-file-")) | .name' > artifact_names.txt
          cat artifact_names.txt

      # - name: Download all artifacts
      #   uses: actions/download-artifact@v4
      #   with:
      #     name: temp-file-*
      #     path: artifacts
      - name: Download and check artifacts
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          mkdir -p artifacts
          for offset in 0 200 400 600 800 1000 1200 1400 1600 1800 2000 2200 2400 2600 2800 3000; do
            echo "Downloading artifact for offset $offset"
            artifact_url=$(gh api -H "Accept: application/vnd.github.v3+json" \
              "/repos/${{ github.repository }}/actions/artifacts" \
              | jq -r --arg NAME "temp-file-$offset" '.artifacts[] | select(.name == $NAME) | .archive_download_url')
            
            if [ -n "$artifact_url" ]; then
              curl -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" -L -o artifacts/temp_$offset.zip "$artifact_url"
              if file artifacts/temp_$offset.zip | grep -q "Zip archive"; then
                echo "Artifact $offset is valid"
              else
                echo "Error: Artifact $offset is not a valid zip file"
                exit 1
              fi
            else
              echo "No artifact found for offset $offset"
            fi
          done


        # - name: Download all artifacts
      #   env:
      #     GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      #   run: |
      #     mkdir artifacts
      #     while IFS= read -r artifact; do
      #       echo "Downloading $artifact"
      #       gh run download $artifact --dir artifacts
      #     done < artifact_names.txt

      - name: Sort and list artifact files
        run: |
          ls artifacts/temp_*.csv | sort -t '_' -k 2 -n > sorted_files.txt
          cat sorted_files.txt
          
      - name: Install pandas
        run: |
          python -m pip install pandas
          sudo apt-get update && sudo apt-get install -y unzip
          
      - name: Delete final_results.csv if it exists
        run: |
          if [ -f final_results.csv ]; then rm final_results.csv; fi

      - name: Unzip all files
        run: |
          for file in artifacts/*.zip; do
            unzip -o "$file" -d artifacts
          done

      - name: Merge CSV files
        run: |
          python merge_csvs.py final_results.csv 'artifacts/temp_*.csv'

      - name: Commit and push consolidated results
        env:
          PAT_TOKEN: ${{ secrets.PAT_TOKEN }}
        run: |
          chmod +x git_update.sh
          ./git_update.sh



